#!/usr/bin/env node
// Scans for *Elm.ts files and regenerates registerElements.ts.
//
// Special constructors (classes that need extra args beyond (0,0)) are listed
// in SPECIAL_CTORS below.  Everything else gets `new FooElm(0, 0)`.

import { readdirSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out  = join(root, "registerElements.ts");

const SKIP = new Set(["ScopeElm", "GateElm", "ChipElm", "CompositeElm"]);

// Classes to add to ElementFactory but not CirSim.register.
// Used when another class's getDumpClass() causes the dump-type mapping,
// but the base class still needs to be constructable by name at load time.
// Value is the source file to import from (defaults to the class name).
const FACTORY_ONLY = {
    TransistorElm: "TransistorElm",
    MosfetElm: "MosfetElm",
};

// Classes that need a non-standard constructor for CirSim.register().
// Value is the argument list as a string (after x, y).
const SPECIAL_CTORS = {
    VoltageElm: "VoltageElm.WF_DC",
};

const elmFiles = readdirSync(root)
    .filter(f => f.endsWith("Elm.ts") && !f.startsWith("Circuit"))
    .map(f => f.replace(/\.ts$/, ""))
    .filter(name => !SKIP.has(name) && !(name in FACTORY_ONLY))
    .sort();

const imports = elmFiles
    .map(name => `import { ${name} } from "./${name}";`)
    .join("\n");

// Extra imports for FACTORY_ONLY classes (some may share a file with a registered class)
const foNames = Object.keys(FACTORY_ONLY).sort();
const foImports = foNames
    .map(name => `import { ${name} } from "./${FACTORY_ONLY[name]}";`)
    .join("\n");

const foFactoryLines = foNames
    .map(name => `    ElementFactory.registerClass("${name}", ${name} as any);`)
    .join("\n");

const factoryLines = elmFiles
    .map(name => `    ElementFactory.registerClass("${name}", ${name} as any);`)
    .join("\n");

const cirSimLines = elmFiles.map(name => {
    const extra = SPECIAL_CTORS[name];
    const args  = extra ? `0, 0, ${extra}` : "0, 0";
    return `    CirSim.theApp.register("${name}", new ${name}(${args}));`;
}).join("\n");

const content = `\
// AUTO-GENERATED by scripts/generateRegistrations.mjs — do not edit by hand

import { ElementFactory } from "./ElementFactory";
import { CirSim } from "./CirSim";
${foImports}
${imports}

export function registerElements(): void {
${foFactoryLines}
${factoryLines}

${cirSimLines}
}
`;

writeFileSync(out, content);
console.log(`Wrote ${elmFiles.length} elements to registerElements.ts`);
